[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "pillow==10.4.0",
    "pymupdf==1.26.3",
    "pytelegrambotapi==4.33.0",
    "python-barcode>=0.16.1",
    "python-telegram-bot==20.7",
    "pytz==2024.2",
    "qrcode[pil]==7.4.2",
    "reportlab==4.2.5",
    "schedule==1.2.2",
    "zxing-cpp==2.3.0",
]
