// AUTO-GENERATED by /tmp/flowsnap/build_fixture.cjs — read-only prod snapshot 2026-08-17.
// Shape == proposed GET /ombor/flow/graph response. DO NOT hand-edit numbers.
import type { GraphFixture } from "./types";

export const FIXTURE: GraphFixture = {
 "generatedAt": "2026-08-17",
 "readOnly": true,
 "source": "GET /ombor/flow/graph (taklif qilingan shakl) — read-only snapshot, RAILWAY prod",
 "containersRaw": [
  {
   "id": 7,
   "name": "C-01",
   "purpose": "raw",
   "loc": "container",
   "cap": 20000,
   "kg": 25000,
   "dona": 50000,
   "positionsCount": 2,
   "byType": {
    "raw": {
     "kg": 25000,
     "dona": 25000,
     "rows": 1
    },
    "finished": {
     "kg": 0,
     "dona": 25000,
     "rows": 1
    }
   },
   "derived": "mixed",
   "dominant": "raw",
   "mismatch": false,
   "items": [
    {
     "wid": 7,
     "product": "Sholcha",
     "sku": null,
     "qty": 25000,
     "kg": 0,
     "ptype": "raw"
    },
    {
     "wid": 7,
     "product": "Sholcha Oq",
     "sku": null,
     "qty": 25000,
     "kg": 0,
     "ptype": "finished"
    }
   ]
  },
  {
   "id": 10,
   "name": "C-04",
   "purpose": "finished",
   "loc": "container",
   "cap": 20000,
   "kg": 6363.3,
   "dona": 0,
   "positionsCount": 7,
   "byType": {
    "finished": {
     "kg": 2093.2999999999997,
     "dona": 0,
     "rows": 5
    },
    "raw": {
     "kg": 4270,
     "dona": 0,
     "rows": 2
    }
   },
   "derived": "mixed",
   "dominant": "raw",
   "mismatch": true,
   "items": [
    {
     "wid": 10,
     "product": "Eshma Xitoy Strupa PP Oq TWS",
     "sku": "TM-000066",
     "qty": 0,
     "kg": 0,
     "ptype": "finished"
    },
    {
     "wid": 10,
     "product": "Polipropilen CF 1000D Yashil",
     "sku": "TM-000062",
     "qty": 0,
     "kg": 0,
     "ptype": "raw"
    },
    {
     "wid": 10,
     "product": "Polipropilen CF 1500D Qora",
     "sku": "TM-000061",
     "qty": 0,
     "kg": 0,
     "ptype": "raw"
    },
    {
     "wid": 10,
     "product": "PP Oq TWS Strupa 12 talik",
     "sku": "TM-000065",
     "qty": 0,
     "kg": 0,
     "ptype": "finished"
    },
    {
     "wid": 10,
     "product": "Strupa Salafan",
     "sku": "TM-000063",
     "qty": 0,
     "kg": 0,
     "ptype": "finished"
    },
    {
     "wid": 10,
     "product": "XB Strupa",
     "sku": "TM-000064",
     "qty": 0,
     "kg": 0,
     "ptype": "finished"
    },
    {
     "wid": 10,
     "product": "Yashil PP TWS Strupa 16 talik",
     "sku": "TM-000022",
     "qty": 0,
     "kg": 0,
     "ptype": "finished"
    }
   ]
  },
  {
   "id": 21,
   "name": "C-15",
   "purpose": "finished",
   "loc": "container",
   "cap": 20000,
   "kg": 13020,
   "dona": 0,
   "positionsCount": 3,
   "byType": {
    "raw": {
     "kg": 13020,
     "dona": 0,
     "rows": 3
    }
   },
   "derived": "raw",
   "dominant": "raw",
   "mismatch": true,
   "items": [
    {
     "wid": 21,
     "product": "Polipropilen CF 1000D Ko'k",
     "sku": "TM-000093",
     "qty": 0,
     "kg": 0,
     "ptype": "raw"
    },
    {
     "wid": 21,
     "product": "Polipropilen CF 1000D Qizil",
     "sku": "TM-000092",
     "qty": 0,
     "kg": 0,
     "ptype": "raw"
    },
    {
     "wid": 21,
     "product": "Polipropilen CF 1000D Sariq",
     "sku": "TM-000094",
     "qty": 0,
     "kg": 0,
     "ptype": "raw"
    }
   ]
  }
 ],
 "containersFinished": [
  {
   "id": 8,
   "name": "C-02",
   "purpose": "finished",
   "loc": "container",
   "cap": 20000,
   "kg": 6053,
   "dona": 0,
   "positionsCount": 10,
   "byType": {
    "finished": {
     "kg": 6053.000000000001,
     "dona": 0,
     "rows": 10
    }
   },
   "derived": "finished",
   "dominant": "finished",
   "mismatch": false,
   "items": [
    {
     "wid": 8,
     "product": "Rangli 2.5 sm ikki qavat lenta",
     "sku": "TM-000053",
     "qty": 0,
     "kg": 0,
     "ptype": "finished"
    },
    {
     "wid": 8,
     "product": "Reels Lenta",
     "sku": "TM-000054",
     "qty": 0,
     "kg": 0,
     "ptype": "finished"
    },
    {
     "wid": 8,
     "product": "Shroki 3.5 Oq",
     "sku": null,
     "qty": 0,
     "kg": 0,
     "ptype": "finished"
    },
    {
     "wid": 8,
     "product": "Shroki 3.5 sm lenta",
     "sku": "TM-000052",
     "qty": 0,
     "kg": 0,
     "ptype": "finished"
    },
    {
     "wid": 8,
     "product": "Tahoe Lenta",
     "sku": "TM-000060",
     "qty": 0,
     "kg": 0,
     "ptype": "finished"
    },
    {
     "wid": 8,
     "product": "Tulpor Lenta Aralash",
     "sku": "TM-000055",
     "qty": 0,
     "kg": 0,
     "ptype": "finished"
    },
    {
     "wid": 8,
     "product": "Tulpor Lenta Ko‘k",
     "sku": "TM-000058",
     "qty": 0,
     "kg": 0,
     "ptype": "finished"
    },
    {
     "wid": 8,
     "product": "Tulpor Lenta Oq",
     "sku": "TM-000057",
     "qty": 0,
     "kg": 0,
     "ptype": "finished"
    },
    {
     "wid": 8,
     "product": "Tulpor lenta qizil",
     "sku": "TM-000059",
     "qty": 0,
     "kg": 0,
     "ptype": "finished"
    },
    {
     "wid": 8,
     "product": "Tulpor Lenta Yashil",
     "sku": "TM-000056",
     "qty": 0,
     "kg": 0,
     "ptype": "finished"
    }
   ]
  },
  {
   "id": 9,
   "name": "C-03",
   "purpose": "raw",
   "loc": "container",
   "cap": 20000,
   "kg": 0,
   "dona": 10000,
   "positionsCount": 1,
   "byType": {
    "finished": {
     "kg": 0,
     "dona": 10000,
     "rows": 1
    }
   },
   "derived": "finished",
   "dominant": "finished",
   "mismatch": true,
   "items": [
    {
     "wid": 9,
     "product": "Sholcha Sariq",
     "sku": null,
     "qty": 10000,
     "kg": 0,
     "ptype": "finished"
    }
   ]
  },
  {
   "id": 11,
   "name": "C-05",
   "purpose": "finished",
   "loc": "container",
   "cap": 20000,
   "kg": 10455.43,
   "dona": 2055,
   "positionsCount": 4,
   "byType": {
    "finished": {
     "kg": 10455.434668121825,
     "dona": 2055,
     "rows": 4
    }
   },
   "derived": "finished",
   "dominant": "finished",
   "mismatch": false,
   "items": [
    {
     "wid": 11,
     "product": "Ikki Qavat Arqon / 4 kg",
     "sku": null,
     "qty": 735,
     "kg": 0,
     "ptype": "finished"
    },
    {
     "wid": 11,
     "product": "Ikki Qavat Arqon / 5 kg",
     "sku": null,
     "qty": 815,
     "kg": 0,
     "ptype": "finished"
    },
    {
     "wid": 11,
     "product": "Ikki Qavat Arqon / 6 kg",
     "sku": null,
     "qty": 479,
     "kg": 0,
     "ptype": "finished"
    },
    {
     "wid": 11,
     "product": "Kurtka Tros 4-5 kg",
     "sku": null,
     "qty": 26,
     "kg": 0,
     "ptype": "finished"
    }
   ]
  },
  {
   "id": 12,
   "name": "C-06",
   "purpose": "finished",
   "loc": "container",
   "cap": 20000,
   "kg": 7435.5,
   "dona": 0,
   "positionsCount": 13,
   "byType": {
    "finished": {
     "kg": 7435.499999999999,
     "dona": 0,
     "rows": 13
    }
   },
   "derived": "finished",
   "dominant": "finished",
   "mismatch": false,
   "items": [
    {
     "wid": 12,
     "product": "Shlanka Polipropilen CF Ko‘k",
     "sku": "TM-000072",
     "qty": 0,
     "kg": 0,
     "ptype": "finished"
    },
    {
     "wid": 12,
     "product": "Shlanka Polipropilen CF Oq",
     "sku": "TM-000074",
     "qty": 0,
     "kg": 0,
     "ptype": "finished"
    },
    {
     "wid": 12,
     "product": "Shlanka Polipropilen CF Qizil",
     "sku": "TM-000073",
     "qty": 0,
     "kg": 0,
     "ptype": "finished"
    },
    {
     "wid": 12,
     "product": "Shlanka Polipropilen CF Qora",
     "sku": "TM-000070",
     "qty": 0,
     "kg": 0,
     "ptype": "finished"
    },
    {
     "wid": 12,
     "product": "Shlanka Polipropilen CF Yashil",
     "sku": "TM-000071",
     "qty": 0,
     "kg": 0,
     "ptype": "finished"
    },
    {
     "wid": 12,
     "product": "Shlanka Polyamide Yumshoq",
     "sku": "TM-000067",
     "qty": 0,
     "kg": 0,
     "ptype": "finished"
    },
    {
     "wid": 12,
     "product": "Shlanka Polyester FDY Ko‘k",
     "sku": "TM-000077",
     "qty": 0,
     "kg": 0,
     "ptype": "finished"
    },
    {
     "wid": 12,
     "product": "Shlanka Polyester FDY Oq",
     "sku": "TM-000079",
     "qty": 0,
     "kg": 0,
     "ptype": "finished"
    },
    {
     "wid": 12,
     "product": "Shlanka Polyester FDY Qizil",
     "sku": "TM-000078",
     "qty": 0,
     "kg": 0,
     "ptype": "finished"
    },
    {
     "wid": 12,
     "product": "Shlanka Polyester FDY Qora",
     "sku": "TM-000075",
     "qty": 0,
     "kg": 0,
     "ptype": "finished"
    },
    {
     "wid": 12,
     "product": "Shlanka Polyester FDY Yashil",
     "sku": "TM-000076",
     "qty": 0,
     "kg": 0,
     "ptype": "finished"
    },
    {
     "wid": 12,
     "product": "Shlanka Tortqi PP Oq TWS — 50 metr",
     "sku": "TM-000068",
     "qty": 0,
     "kg": 0,
     "ptype": "finished"
    },
    {
     "wid": 12,
     "product": "Shlanka Tortqi PP Yashil TWS — 50 metr",
     "sku": "TM-000069",
     "qty": 0,
     "kg": 0,
     "ptype": "finished"
    }
   ]
  },
  {
   "id": 14,
   "name": "C-08",
   "purpose": "raw",
   "loc": "container",
   "cap": 20000,
   "kg": 0,
   "dona": 25000,
   "positionsCount": 1,
   "byType": {
    "finished": {
     "kg": 0,
     "dona": 25000,
     "rows": 1
    }
   },
   "derived": "finished",
   "dominant": "finished",
   "mismatch": true,
   "items": [
    {
     "wid": 14,
     "product": "Sholcha Sariq",
     "sku": null,
     "qty": 25000,
     "kg": 0,
     "ptype": "finished"
    }
   ]
  },
  {
   "id": 15,
   "name": "C-09",
   "purpose": "raw",
   "loc": "container",
   "cap": 20000,
   "kg": 0,
   "dona": 22000,
   "positionsCount": 1,
   "byType": {
    "finished": {
     "kg": 0,
     "dona": 22000,
     "rows": 1
    }
   },
   "derived": "finished",
   "dominant": "finished",
   "mismatch": true,
   "items": [
    {
     "wid": 15,
     "product": "Sholcha Oq",
     "sku": null,
     "qty": 22000,
     "kg": 0,
     "ptype": "finished"
    }
   ]
  },
  {
   "id": 19,
   "name": "C-13",
   "purpose": "raw",
   "loc": "container",
   "cap": 20000,
   "kg": 0,
   "dona": 25000,
   "positionsCount": 1,
   "byType": {
    "finished": {
     "kg": 0,
     "dona": 25000,
     "rows": 1
    }
   },
   "derived": "finished",
   "dominant": "finished",
   "mismatch": true,
   "items": [
    {
     "wid": 19,
     "product": "Sholcha Sariq",
     "sku": null,
     "qty": 25000,
     "kg": 0,
     "ptype": "finished"
    }
   ]
  },
  {
   "id": 22,
   "name": "C-16",
   "purpose": "finished",
   "loc": "container",
   "cap": 20000,
   "kg": 7045.2,
   "dona": 61080,
   "positionsCount": 3,
   "byType": {
    "finished": {
     "kg": 7045.2,
     "dona": 61080,
     "rows": 3
    }
   },
   "derived": "finished",
   "dominant": "finished",
   "mismatch": false,
   "items": [
    {
     "wid": 22,
     "product": "Qop ip 100 talik",
     "sku": "TM-000080",
     "qty": 55200,
     "kg": 0,
     "ptype": "finished"
    },
    {
     "wid": 22,
     "product": "Qop ip 120 talik",
     "sku": "TM-000081",
     "qty": 2520,
     "kg": 0,
     "ptype": "finished"
    },
    {
     "wid": 22,
     "product": "Qop ip 80 talik",
     "sku": "TM-000082",
     "qty": 3360,
     "kg": 0,
     "ptype": "finished"
    }
   ]
  },
  {
   "id": 23,
   "name": "C-17",
   "purpose": "finished",
   "loc": "container",
   "cap": 20000,
   "kg": 3256,
   "dona": 65280,
   "positionsCount": 9,
   "byType": {
    "finished": {
     "kg": 3256,
     "dona": 65280,
     "rows": 9
    }
   },
   "derived": "finished",
   "dominant": "finished",
   "mismatch": false,
   "items": [
    {
     "wid": 23,
     "product": "Qop ip 100 gramm Oq",
     "sku": "TM-000091",
     "qty": 4320,
     "kg": 0,
     "ptype": "finished"
    },
    {
     "wid": 23,
     "product": "Qop ip 100 gramm Qora",
     "sku": "TM-000089",
     "qty": 2080,
     "kg": 0,
     "ptype": "finished"
    },
    {
     "wid": 23,
     "product": "Qop ip 100 gramm Sariq",
     "sku": "TM-000090",
     "qty": 2880,
     "kg": 0,
     "ptype": "finished"
    },
    {
     "wid": 23,
     "product": "Qop ip 30 gramm Oq",
     "sku": "TM-000088",
     "qty": 8400,
     "kg": 0,
     "ptype": "finished"
    },
    {
     "wid": 23,
     "product": "Qop ip 30 gramm Qora",
     "sku": "TM-000086",
     "qty": 4800,
     "kg": 0,
     "ptype": "finished"
    },
    {
     "wid": 23,
     "product": "Qop ip 30 gramm Sariq",
     "sku": "TM-000087",
     "qty": 10400,
     "kg": 0,
     "ptype": "finished"
    },
    {
     "wid": 23,
     "product": "Qop ip 50 gramm Oq",
     "sku": "TM-000085",
     "qty": 7600,
     "kg": 0,
     "ptype": "finished"
    },
    {
     "wid": 23,
     "product": "Qop ip 50 gramm Qora",
     "sku": "TM-000083",
     "qty": 12000,
     "kg": 0,
     "ptype": "finished"
    },
    {
     "wid": 23,
     "product": "Qop ip 50 gramm Sariq",
     "sku": "TM-000084",
     "qty": 12800,
     "kg": 0,
     "ptype": "finished"
    }
   ]
  },
  {
   "id": 24,
   "name": "C-18",
   "purpose": "finished",
   "loc": "container",
   "cap": 20000,
   "kg": 9839.45,
   "dona": 0,
   "positionsCount": 29,
   "byType": {
    "finished": {
     "kg": 9839.45,
     "dona": 0,
     "rows": 29
    }
   },
   "derived": "finished",
   "dominant": "finished",
   "mismatch": false,
   "items": [
    {
     "wid": 24,
     "product": "Alpinist 10 mm",
     "sku": "TM-000047",
     "qty": 0,
     "kg": 0,
     "ptype": "finished"
    },
    {
     "wid": 24,
     "product": "Alpinist 12 mm",
     "sku": "TM-000046",
     "qty": 0,
     "kg": 0,
     "ptype": "finished"
    },
    {
     "wid": 24,
     "product": "Alpinist 14 mm",
     "sku": "TM-000048",
     "qty": 0,
     "kg": 0,
     "ptype": "finished"
    },
    {
     "wid": 24,
     "product": "Alpinist 16 mm",
     "sku": "TM-000049",
     "qty": 0,
     "kg": 0,
     "ptype": "finished"
    },
    {
     "wid": 24,
     "product": "Alpinist 20 mm",
     "sku": "TM-000050",
     "qty": 0,
     "kg": 0,
     "ptype": "finished"
    },
    {
     "wid": 24,
     "product": "Alpinist 25 mm",
     "sku": "TM-000051",
     "qty": 0,
     "kg": 0,
     "ptype": "finished"
    },
    {
     "wid": 24,
     "product": "FDY Fil Arqon",
     "sku": "TM-000033",
     "qty": 0,
     "kg": 0,
     "ptype": "finished"
    },
    {
     "wid": 24,
     "product": "FDY Tros Aralash",
     "sku": "TM-000039",
     "qty": 0,
     "kg": 0,
     "ptype": "finished"
    },
    {
     "wid": 24,
     "product": "Kanob Aralash 20 metr",
     "sku": "TM-000045",
     "qty": 0,
     "kg": 0,
     "ptype": "finished"
    },
    {
     "wid": 24,
     "product": "Rossiya Tros",
     "sku": null,
     "qty": 0,
     "kg": 0,
     "ptype": "finished"
    },
    {
     "wid": 24,
     "product": "Toshkent Arqon 10 mm Ko‘k",
     "sku": "TM-000032",
     "qty": 0,
     "kg": 0,
     "ptype": "finished"
    },
    {
     "wid": 24,
     "product": "Toshkent Arqon 10 mm Yashil",
     "sku": "TM-000027",
     "qty": 0,
     "kg": 0,
     "ptype": "finished"
    },
    {
     "wid": 24,
     "product": "Toshkent Arqon 12 mm Qizil",
     "sku": "TM-000030",
     "qty": 0,
     "kg": 0,
     "ptype": "finished"
    },
    {
     "wid": 24,
     "product": "Toshkent Arqon 12 mm Qora Ichki Polyamide Sariq",
     "sku": "TM-000029",
     "qty": 0,
     "kg": 0,
     "ptype": "finished"
    },
    {
     "wid": 24,
     "product": "Toshkent Arqon 12 mm Sariq",
     "sku": "TM-000038",
     "qty": 0,
     "kg": 0,
     "ptype": "finished"
    },
    {
     "wid": 24,
     "product": "Toshkent Arqon 14 mm Oq — 100 metr",
     "sku": "TM-000035",
     "qty": 0,
     "kg": 0,
     "ptype": "finished"
    },
    {
     "wid": 24,
     "product": "Toshkent Arqon 14 mm Qizil",
     "sku": "TM-000028",
     "qty": 0,
     "kg": 0,
     "ptype": "finished"
    },
    {
     "wid": 24,
     "product": "Toshkent Arqon 14 mm Qora",
     "sku": "TM-000031",
     "qty": 0,
     "kg": 0,
     "ptype": "finished"
    },
    {
     "wid": 24,
     "product": "Toshkent Arqon 16 mm Ko‘k",
     "sku": "TM-000024",
     "qty": 0,
     "kg": 0,
     "ptype": "finished"
    },
    {
     "wid": 24,
     "product": "Toshkent Arqon 16 mm Oq",
     "sku": "TM-000036",
     "qty": 0,
     "kg": 0,
     "ptype": "finished"
    },
    {
     "wid": 24,
     "product": "Toshkent Arqon 16 mm Oq — 50 metr",
     "sku": "TM-000034",
     "qty": 0,
     "kg": 0,
     "ptype": "finished"
    },
    {
     "wid": 24,
     "product": "Toshkent Arqon 16 mm Qora",
     "sku": "TM-000025",
     "qty": 0,
     "kg": 0,
     "ptype": "finished"
    },
    {
     "wid": 24,
     "product": "Toshkent Arqon Qora 16 mm Ichki Polyamide Sariq",
     "sku": "TM-000037",
     "qty": 0,
     "kg": 0,
     "ptype": "finished"
    },
    {
     "wid": 24,
     "product": "Usti gilam ichki Sariq Polyamide Arqon",
     "sku": "TM-000040",
     "qty": 0,
     "kg": 0,
     "ptype": "finished"
    },
    {
     "wid": 24,
     "product": "Ustki 187 TWS Oq ichki Strupa 14 mm Arqon",
     "sku": "TM-000044",
     "qty": 0,
     "kg": 0,
     "ptype": "finished"
    },
    {
     "wid": 24,
     "product": "Ustki 187 TWS Oq ichki Zubr 16 mm Arqon",
     "sku": "TM-000043",
     "qty": 0,
     "kg": 0,
     "ptype": "finished"
    },
    {
     "wid": 24,
     "product": "Ustki Gilam Ichki Sariq Polyamide",
     "sku": "TM-000026",
     "qty": 0,
     "kg": 0,
     "ptype": "finished"
    },
    {
     "wid": 24,
     "product": "Ustki Oq TWS ichki Polyamide Oq Arqon",
     "sku": "TM-000041",
     "qty": 0,
     "kg": 0,
     "ptype": "finished"
    },
    {
     "wid": 24,
     "product": "Ustki PP xom ichki Polyamide Oq Arqon",
     "sku": "TM-000042",
     "qty": 0,
     "kg": 0,
     "ptype": "finished"
    }
   ]
  },
  {
   "id": 25,
   "name": "C-19",
   "purpose": "finished",
   "loc": "container",
   "cap": 20000,
   "kg": 8713.3,
   "dona": 0,
   "positionsCount": 13,
   "byType": {
    "finished": {
     "kg": 5094.65,
     "dona": 0,
     "rows": 10
    },
    "raw": {
     "kg": 646,
     "dona": 0,
     "rows": 1
    },
    "pre-finished": {
     "kg": 2972.6499999999996,
     "dona": 0,
     "rows": 2
    }
   },
   "derived": "mixed",
   "dominant": "finished",
   "mismatch": false,
   "items": [
    {
     "wid": 25,
     "product": "Passport Strupa 16 talik",
     "sku": "TM-000020",
     "qty": 0,
     "kg": 0,
     "ptype": "finished"
    },
    {
     "wid": 25,
     "product": "Passport Strupa 24 talik",
     "sku": "TM-000021",
     "qty": 0,
     "kg": 0,
     "ptype": "finished"
    },
    {
     "wid": 25,
     "product": "Passport Xom BCF",
     "sku": "TM-000018",
     "qty": 0,
     "kg": 0,
     "ptype": "raw"
    },
    {
     "wid": 25,
     "product": "Polyamide 144 oq TWS",
     "sku": "TM-000011",
     "qty": 0,
     "kg": 0,
     "ptype": "finished"
    },
    {
     "wid": 25,
     "product": "Polyamide Ko‘k 187 TWS",
     "sku": "TM-000012",
     "qty": 0,
     "kg": 0,
     "ptype": "finished"
    },
    {
     "wid": 25,
     "product": "Polyamide Oq 187 TWS",
     "sku": "TM-000015",
     "qty": 0,
     "kg": 0,
     "ptype": "finished"
    },
    {
     "wid": 25,
     "product": "Polyamide Qizil 187 TWS",
     "sku": "TM-000013",
     "qty": 0,
     "kg": 0,
     "ptype": "finished"
    },
    {
     "wid": 25,
     "product": "Polyamide Sariq 187 TWS",
     "sku": "TM-000014",
     "qty": 0,
     "kg": 0,
     "ptype": "finished"
    },
    {
     "wid": 25,
     "product": "Qop ip Qizil",
     "sku": "TM-000017",
     "qty": 0,
     "kg": 0,
     "ptype": "pre-finished"
    },
    {
     "wid": 25,
     "product": "Qop ip Yashil",
     "sku": "TM-000016",
     "qty": 0,
     "kg": 0,
     "ptype": "pre-finished"
    },
    {
     "wid": 25,
     "product": "Sariq Polyester Strupa 16 talik",
     "sku": "TM-000023",
     "qty": 0,
     "kg": 0,
     "ptype": "finished"
    },
    {
     "wid": 25,
     "product": "Yashil PP TWS Strupa 16 talik",
     "sku": "TM-000022",
     "qty": 0,
     "kg": 0,
     "ptype": "finished"
    },
    {
     "wid": 25,
     "product": "Yashil PP TWS Strupa 24 talik",
     "sku": "TM-000019",
     "qty": 0,
     "kg": 0,
     "ptype": "finished"
    }
   ]
  },
  {
   "id": 26,
   "name": "C-20",
   "purpose": "finished",
   "loc": "container",
   "cap": 20000,
   "kg": 10136.45,
   "dona": 0,
   "positionsCount": 10,
   "byType": {
    "finished": {
     "kg": 5564.200000000001,
     "dona": 0,
     "rows": 9
    },
    "pre-finished": {
     "kg": 4572.25,
     "dona": 0,
     "rows": 1
    }
   },
   "derived": "mixed",
   "dominant": "finished",
   "mismatch": false,
   "items": [
    {
     "wid": 26,
     "product": "14 mm Alpinist",
     "sku": "TM-000008",
     "qty": 0,
     "kg": 0,
     "ptype": "finished"
    },
    {
     "wid": 26,
     "product": "16 mm Alpinist",
     "sku": "TM-000007",
     "qty": 0,
     "kg": 0,
     "ptype": "finished"
    },
    {
     "wid": 26,
     "product": "FDY Igna Strupa",
     "sku": "TM-000005",
     "qty": 0,
     "kg": 0,
     "ptype": "pre-finished"
    },
    {
     "wid": 26,
     "product": "Neylon 210D / 45",
     "sku": "TM-000001",
     "qty": 0,
     "kg": 0,
     "ptype": "finished"
    },
    {
     "wid": 26,
     "product": "Neylon 210D / 60",
     "sku": "TM-000002",
     "qty": 0,
     "kg": 0,
     "ptype": "finished"
    },
    {
     "wid": 26,
     "product": "Neylon 210D / 90",
     "sku": "TM-000003",
     "qty": 0,
     "kg": 0,
     "ptype": "finished"
    },
    {
     "wid": 26,
     "product": "Toshkent Oq 14 mm — Bir qavat",
     "sku": "TM-000004",
     "qty": 0,
     "kg": 0,
     "ptype": "finished"
    },
    {
     "wid": 26,
     "product": "Toshkent Oq 16 mm Ichi Oq PP TWS — 50 metr",
     "sku": "TM-000010",
     "qty": 0,
     "kg": 0,
     "ptype": "finished"
    },
    {
     "wid": 26,
     "product": "Toshkent Qora 14 mm Ichi Oq PP TWS",
     "sku": "TM-000009",
     "qty": 0,
     "kg": 0,
     "ptype": "finished"
    },
    {
     "wid": 26,
     "product": "Toshkent Qora 14 mm Ichki Sariq",
     "sku": "TM-000006",
     "qty": 0,
     "kg": 0,
     "ptype": "finished"
    }
   ]
  }
 ],
 "emptyContainers": [
  {
   "id": 13,
   "name": "C-07",
   "purpose": "finished",
   "loc": "container",
   "cap": 20000,
   "kg": 0,
   "dona": 0,
   "positionsCount": 0,
   "byType": {},
   "derived": "empty",
   "dominant": null,
   "mismatch": false,
   "items": []
  },
  {
   "id": 16,
   "name": "C-10",
   "purpose": "raw",
   "loc": "container",
   "cap": 20000,
   "kg": 0,
   "dona": 0,
   "positionsCount": 0,
   "byType": {},
   "derived": "empty",
   "dominant": null,
   "mismatch": false,
   "items": []
  },
  {
   "id": 17,
   "name": "C-11",
   "purpose": "finished",
   "loc": "container",
   "cap": 20000,
   "kg": 0,
   "dona": 0,
   "positionsCount": 0,
   "byType": {},
   "derived": "empty",
   "dominant": null,
   "mismatch": false,
   "items": []
  },
  {
   "id": 18,
   "name": "C-12",
   "purpose": "finished",
   "loc": "container",
   "cap": 20000,
   "kg": 0,
   "dona": 0,
   "positionsCount": 0,
   "byType": {},
   "derived": "empty",
   "dominant": null,
   "mismatch": false,
   "items": []
  },
  {
   "id": 20,
   "name": "C-14",
   "purpose": "finished",
   "loc": "container",
   "cap": 20000,
   "kg": 0,
   "dona": 0,
   "positionsCount": 0,
   "byType": {},
   "derived": "empty",
   "dominant": null,
   "mismatch": false,
   "items": []
  },
  {
   "id": 27,
   "name": "C-21",
   "purpose": "finished",
   "loc": "container",
   "cap": 20000,
   "kg": 0,
   "dona": 0,
   "positionsCount": 0,
   "byType": {},
   "derived": "empty",
   "dominant": null,
   "mismatch": false,
   "items": []
  },
  {
   "id": 28,
   "name": "C-22",
   "purpose": "finished",
   "loc": "container",
   "cap": 20000,
   "kg": 0,
   "dona": 0,
   "positionsCount": 0,
   "byType": {},
   "derived": "empty",
   "dominant": null,
   "mismatch": false,
   "items": []
  },
  {
   "id": 29,
   "name": "C-23",
   "purpose": "finished",
   "loc": "container",
   "cap": 20000,
   "kg": 0,
   "dona": 0,
   "positionsCount": 0,
   "byType": {},
   "derived": "empty",
   "dominant": null,
   "mismatch": false,
   "items": []
  },
  {
   "id": 30,
   "name": "C-24",
   "purpose": "finished",
   "loc": "container",
   "cap": 20000,
   "kg": 0,
   "dona": 0,
   "positionsCount": 0,
   "byType": {},
   "derived": "empty",
   "dominant": null,
   "mismatch": false,
   "items": []
  },
  {
   "id": 31,
   "name": "C-25",
   "purpose": "finished",
   "loc": "container",
   "cap": 20000,
   "kg": 0,
   "dona": 0,
   "positionsCount": 0,
   "byType": {},
   "derived": "empty",
   "dominant": null,
   "mismatch": false,
   "items": []
  },
  {
   "id": 32,
   "name": "C-26",
   "purpose": "finished",
   "loc": "container",
   "cap": 20000,
   "kg": 0,
   "dona": 0,
   "positionsCount": 0,
   "byType": {},
   "derived": "empty",
   "dominant": null,
   "mismatch": false,
   "items": []
  },
  {
   "id": 33,
   "name": "C-27",
   "purpose": "finished",
   "loc": "container",
   "cap": 20000,
   "kg": 0,
   "dona": 0,
   "positionsCount": 0,
   "byType": {},
   "derived": "empty",
   "dominant": null,
   "mismatch": false,
   "items": []
  },
  {
   "id": 34,
   "name": "C-28",
   "purpose": "finished",
   "loc": "container",
   "cap": 20000,
   "kg": 0,
   "dona": 0,
   "positionsCount": 0,
   "byType": {},
   "derived": "empty",
   "dominant": null,
   "mismatch": false,
   "items": []
  },
  {
   "id": 35,
   "name": "C-29",
   "purpose": "finished",
   "loc": "container",
   "cap": 20000,
   "kg": 0,
   "dona": 0,
   "positionsCount": 0,
   "byType": {},
   "derived": "empty",
   "dominant": null,
   "mismatch": false,
   "items": []
  },
  {
   "id": 36,
   "name": "C-30",
   "purpose": "finished",
   "loc": "container",
   "cap": 20000,
   "kg": 0,
   "dona": 0,
   "positionsCount": 0,
   "byType": {},
   "derived": "empty",
   "dominant": null,
   "mismatch": false,
   "items": []
  }
 ],
 "regionalGroup": {
  "name": "Viloyat / boshqa omborlar",
  "count": 6,
  "kg": 0,
  "dona": 0,
  "list": [
   {
    "id": 1,
    "name": "Namangan Markaziy Ombor",
    "purpose": "finished",
    "loc": "general",
    "cap": 20000,
    "kg": 0,
    "dona": 0,
    "positionsCount": 0,
    "byType": {},
    "derived": "empty",
    "dominant": null,
    "mismatch": false,
    "items": []
   },
   {
    "id": 2,
    "name": "Namangan-1",
    "purpose": "finished",
    "loc": "general",
    "cap": 20000,
    "kg": 0,
    "dona": 0,
    "positionsCount": 0,
    "byType": {},
    "derived": "empty",
    "dominant": null,
    "mismatch": false,
    "items": []
   },
   {
    "id": 3,
    "name": "Namangan-2",
    "purpose": "finished",
    "loc": "general",
    "cap": 20000,
    "kg": 0,
    "dona": 0,
    "positionsCount": 0,
    "byType": {},
    "derived": "empty",
    "dominant": null,
    "mismatch": false,
    "items": []
   },
   {
    "id": 4,
    "name": "Andijon Ombori",
    "purpose": "finished",
    "loc": "general",
    "cap": 20000,
    "kg": 0,
    "dona": 0,
    "positionsCount": 0,
    "byType": {},
    "derived": "empty",
    "dominant": null,
    "mismatch": false,
    "items": []
   },
   {
    "id": 5,
    "name": "Fargona Ombori",
    "purpose": "finished",
    "loc": "general",
    "cap": 20000,
    "kg": 0,
    "dona": 0,
    "positionsCount": 0,
    "byType": {},
    "derived": "empty",
    "dominant": null,
    "mismatch": false,
    "items": []
   },
   {
    "id": 6,
    "name": "Toshkent Ombori",
    "purpose": "finished",
    "loc": "general",
    "cap": 20000,
    "kg": 0,
    "dona": 0,
    "positionsCount": 0,
    "byType": {},
    "derived": "empty",
    "dominant": null,
    "mismatch": false,
    "items": []
   }
  ]
 },
 "departments": [
  {
   "id": 6,
   "name": "Arqon Bo'lim 3",
   "workers": [
    {
     "worker": "Aziza",
     "role": "IShlabchiqaruvchi"
    },
    {
     "worker": "Gullola",
     "role": "IShlabchiqaruvchi"
    },
    {
     "worker": "Xusnida",
     "role": "IShlabchiqaruvchi"
    },
    {
     "worker": "Dilnoza",
     "role": "packaging"
    },
    {
     "worker": "Dilnoza",
     "role": "pock"
    },
    {
     "worker": "Madina M",
     "role": "pock"
    },
    {
     "worker": "Zulxumor",
     "role": "preparation"
    },
    {
     "worker": "Aziza",
     "role": "producer"
    },
    {
     "worker": "Gullola",
     "role": "producer"
    },
    {
     "worker": "Shohida",
     "role": "producer"
    },
    {
     "worker": "Zulxumor",
     "role": "Uvopchi"
    }
   ],
   "roles": [
    {
     "roleKey": "IShlabchiqaruvchi",
     "label": "Chiqaruvchi",
     "rate": 1125,
     "payMode": "individual",
     "maxWorkers": 5
    },
    {
     "roleKey": "pock",
     "label": "Pochkalash",
     "rate": 750,
     "payMode": "pooled",
     "maxWorkers": 2
    },
    {
     "roleKey": "Uvopchi",
     "label": "Ip O'rovchi",
     "rate": 375,
     "payMode": "pooled",
     "maxWorkers": 5
    }
   ],
   "wipKg": -8964.77,
   "wipRows": 171,
   "salary": {
    "entries": 21,
    "workers": 7,
    "total": 3244162.5,
    "lastDate": "2026-06-30"
   },
   "salaryByWorker": [
    {
     "worker": "Aziza",
     "total": 538687.5,
     "entries": 3,
     "last": "2026-06-30"
    },
    {
     "worker": "Dilnoza",
     "total": 540693.75,
     "entries": 4,
     "last": "2026-06-30"
    },
    {
     "worker": "Gullola",
     "total": 548812.5,
     "entries": 3,
     "last": "2026-06-30"
    },
    {
     "worker": "Madina M",
     "total": 540693.75,
     "entries": 3,
     "last": "2026-06-30"
    },
    {
     "worker": "Sarvarbek",
     "total": 0,
     "entries": 1,
     "last": "2026-06-24"
    },
    {
     "worker": "Shohida",
     "total": 534581.25,
     "entries": 3,
     "last": "2026-06-30"
    },
    {
     "worker": "Zulxumor",
     "total": 540693.75,
     "entries": 4,
     "last": "2026-06-30"
    }
   ],
   "produce": [
    {
     "product": "Ikki Qavat Arqon / 4 kg",
     "kg": 2995.95,
     "n": 72,
     "first": "2026-07-06",
     "last": "2026-08-15"
    },
    {
     "product": "Ikki Qavat Arqon / 5 kg",
     "kg": 3250.99,
     "n": 51,
     "first": "2026-07-06",
     "last": "2026-08-15"
    },
    {
     "product": "Ikki Qavat Arqon / 6 kg",
     "kg": 2565.93,
     "n": 45,
     "first": "2026-07-06",
     "last": "2026-08-10"
    },
    {
     "product": "Kurtka Tros 4-5 kg",
     "kg": 151.9,
     "n": 3,
     "first": "2026-07-25",
     "last": "2026-07-25"
    }
   ],
   "batches": [
    {
     "product": "Ikki Qavat Arqon / 4 kg",
     "kg": 3552.3,
     "dona": 864,
     "n": 85,
     "last": "2026-08-15"
    },
    {
     "product": "Ikki Qavat Arqon / 5 kg",
     "kg": 4416.94,
     "dona": 885,
     "n": 66,
     "last": "2026-08-15"
    },
    {
     "product": "Ikki Qavat Arqon / 6 kg",
     "kg": 3300.53,
     "dona": 566,
     "n": 54,
     "last": "2026-08-10"
    },
    {
     "product": "Kurtka Tros 4-5 kg",
     "kg": 151.9,
     "dona": 26,
     "n": 3,
     "last": "2026-07-25"
    }
   ],
   "bomInputs": [
    {
     "material": "Polipropilen 2 x 1500 / OQ",
     "perUnit": 4,
     "stock": -12247.3,
     "currency": "USD",
     "product": "Ikki Qavat Arqon / 4 kg"
    },
    {
     "material": "Polipropilen 2 x 1500 / OQ",
     "perUnit": 5,
     "stock": -12247.3,
     "currency": "USD",
     "product": "Ikki Qavat Arqon / 5 kg"
    },
    {
     "material": "Polipropilen 2 x 1500 / OQ",
     "perUnit": 6,
     "stock": -12247.3,
     "currency": "USD",
     "product": "Ikki Qavat Arqon / 6 kg"
    },
    {
     "material": "Polipropilen BSF",
     "perUnit": 4.5,
     "stock": -117,
     "currency": "USD",
     "product": "Kurtka Tros 4-5 kg"
    }
   ]
  },
  {
   "id": 9,
   "name": "Qop Ip",
   "workers": [
    {
     "worker": "Hilolaxon",
     "role": "karopkalash"
    },
    {
     "worker": "Muxtasarxon",
     "role": "Qopiporash"
    }
   ],
   "roles": [
    {
     "roleKey": "Qopiporash",
     "label": "o'rash",
     "rate": 100,
     "payMode": "pooled",
     "maxWorkers": 3
    },
    {
     "roleKey": "karopkalash",
     "label": "upakovkachi",
     "rate": 60,
     "payMode": "pooled",
     "maxWorkers": 5
    }
   ],
   "wipKg": 0,
   "wipRows": 0,
   "salary": {
    "entries": 8,
    "workers": 2,
    "total": 480000,
    "lastDate": "2026-06-30"
   },
   "salaryByWorker": [
    {
     "worker": "Hilolaxon",
     "total": 180000,
     "entries": 4,
     "last": "2026-06-30"
    },
    {
     "worker": "Muxtasarxon",
     "total": 300000,
     "entries": 4,
     "last": "2026-06-30"
    }
   ],
   "produce": [],
   "batches": [
    {
     "product": "Qop Ip - 100 talik",
     "kg": 300,
     "dona": 3000,
     "n": 1,
     "last": "2026-06-24"
    }
   ],
   "bomInputs": [
    {
     "material": "Qop ip",
     "perUnit": 0.085,
     "stock": -255,
     "currency": "USD",
     "product": "Qop Ip - 100 talik"
    }
   ]
  },
  {
   "id": 8,
   "name": "Lenta 1",
   "workers": [],
   "roles": [
    {
     "roleKey": "Svoynikvaupakovka",
     "label": "o'rash va pochkalash",
     "rate": 1350,
     "payMode": "pooled",
     "maxWorkers": 2
    },
    {
     "roleKey": "producer",
     "label": "chiqarish",
     "rate": 1350,
     "payMode": "pooled",
     "maxWorkers": 5
    }
   ],
   "wipKg": 0,
   "wipRows": 0,
   "salary": {
    "entries": 0,
    "workers": 0,
    "total": 0,
    "lastDate": null
   },
   "salaryByWorker": [],
   "produce": [],
   "batches": [],
   "bomInputs": []
  }
 ],
 "inactiveDepartments": [
  {
   "id": 10,
   "name": "Arqon Bo'limi"
  },
  {
   "id": 97,
   "name": "Naycha"
  }
 ],
 "wip": [
  {
   "lineId": 6,
   "lineName": "Arqon Bo'lim 3",
   "balanceKg": -8964.77,
   "rows": 171,
   "produceKg": 8964.77,
   "receiveKg": 0,
   "status": "NEGATIVE",
   "first": "2026-07-06",
   "last": "2026-08-15"
  },
  {
   "lineId": 9,
   "lineName": "Qop Ip",
   "balanceKg": 0,
   "rows": 0,
   "produceKg": 0,
   "receiveKg": 0,
   "status": "NO_LEDGER",
   "first": null,
   "last": null
  },
  {
   "lineId": 8,
   "lineName": "Lenta 1",
   "balanceKg": 0,
   "rows": 0,
   "produceKg": 0,
   "receiveKg": 0,
   "status": "NO_LEDGER",
   "first": null,
   "last": null
  }
 ],
 "products": [
  {
   "key": "p-ikkiqavatarqon4kg",
   "name": "Ikki Qavat Arqon / 4 kg",
   "sku": null,
   "lineIds": [
    6
   ],
   "producedKg": 2995.95,
   "batchKg": 3552.3,
   "batchDona": 864,
   "placements": [
    {
     "wid": 11,
     "container": "C-05",
     "kg": 3431.895895522388,
     "qty": 735,
     "ptype": "finished",
     "skuInContainer": null
    }
   ],
   "bom": [
    {
     "material": "Polipropilen 2 x 1500 / OQ",
     "perUnit": 4,
     "stock": -12247.3,
     "currency": "USD"
    }
   ]
  },
  {
   "key": "p-ikkiqavatarqon5kg",
   "name": "Ikki Qavat Arqon / 5 kg",
   "sku": null,
   "lineIds": [
    6
   ],
   "producedKg": 3250.99,
   "batchKg": 4416.94,
   "batchDona": 885,
   "placements": [
    {
     "wid": 11,
     "container": "C-05",
     "kg": 4058.972894736842,
     "qty": 815,
     "ptype": "finished",
     "skuInContainer": null
    }
   ],
   "bom": [
    {
     "material": "Polipropilen 2 x 1500 / OQ",
     "perUnit": 5,
     "stock": -12247.3,
     "currency": "USD"
    }
   ]
  },
  {
   "key": "p-ikkiqavatarqon6kg",
   "name": "Ikki Qavat Arqon / 6 kg",
   "sku": null,
   "lineIds": [
    6
   ],
   "producedKg": 2565.93,
   "batchKg": 3300.53,
   "batchDona": 566,
   "placements": [
    {
     "wid": 11,
     "container": "C-05",
     "kg": 2812.6658778625956,
     "qty": 479,
     "ptype": "finished",
     "skuInContainer": null
    }
   ],
   "bom": [
    {
     "material": "Polipropilen 2 x 1500 / OQ",
     "perUnit": 6,
     "stock": -12247.3,
     "currency": "USD"
    }
   ]
  },
  {
   "key": "p-kurtkatros45kg",
   "name": "Kurtka Tros 4-5 kg",
   "sku": null,
   "lineIds": [
    6
   ],
   "producedKg": 151.9,
   "batchKg": 151.9,
   "batchDona": 26,
   "placements": [
    {
     "wid": 11,
     "container": "C-05",
     "kg": 151.9,
     "qty": 26,
     "ptype": "finished",
     "skuInContainer": null
    }
   ],
   "bom": [
    {
     "material": "Polipropilen BSF",
     "perUnit": 4.5,
     "stock": -117,
     "currency": "USD"
    }
   ]
  },
  {
   "key": "p-qopip100talik",
   "name": "Qop Ip - 100 talik",
   "sku": "TM-000080",
   "lineIds": [
    9
   ],
   "producedKg": 0,
   "batchKg": 300,
   "batchDona": 3000,
   "placements": [
    {
     "wid": 22,
     "container": "C-16",
     "kg": 6348,
     "qty": 55200,
     "ptype": "finished",
     "skuInContainer": "TM-000080"
    }
   ],
   "bom": [
    {
     "material": "Qop ip",
     "perUnit": 0.085,
     "stock": -255,
     "currency": "USD"
    }
   ]
  }
 ],
 "edges": [
  {
   "id": "e-0",
   "kind": "dept-wip",
   "source": "d-6",
   "target": "w-6",
   "table": "wip_movements",
   "joinBasis": "line_id (FK)",
   "rows": 171,
   "kg": 8964.77,
   "note": "PRODUCE yozuvlari; RECEIVE tomoni 0"
  },
  {
   "id": "e-1",
   "kind": "wip-product",
   "source": "w-6",
   "target": "p-ikkiqavatarqon4kg",
   "table": "wip_movements (PRODUCE)",
   "joinBasis": "line_id + product (text)",
   "kg": 2995.95,
   "rows": 72,
   "first": "2026-07-06",
   "last": "2026-08-15"
  },
  {
   "id": "e-2",
   "kind": "wip-product",
   "source": "w-6",
   "target": "p-ikkiqavatarqon5kg",
   "table": "wip_movements (PRODUCE)",
   "joinBasis": "line_id + product (text)",
   "kg": 3250.99,
   "rows": 51,
   "first": "2026-07-06",
   "last": "2026-08-15"
  },
  {
   "id": "e-3",
   "kind": "wip-product",
   "source": "w-6",
   "target": "p-ikkiqavatarqon6kg",
   "table": "wip_movements (PRODUCE)",
   "joinBasis": "line_id + product (text)",
   "kg": 2565.93,
   "rows": 45,
   "first": "2026-07-06",
   "last": "2026-08-10"
  },
  {
   "id": "e-4",
   "kind": "wip-product",
   "source": "w-6",
   "target": "p-kurtkatros45kg",
   "table": "wip_movements (PRODUCE)",
   "joinBasis": "line_id + product (text)",
   "kg": 151.9,
   "rows": 3,
   "first": "2026-07-25",
   "last": "2026-07-25"
  },
  {
   "id": "e-5",
   "kind": "batch-product",
   "source": "d-9",
   "target": "p-qopip100talik",
   "table": "batches",
   "joinBasis": "production_line_id (FK) + product (text)",
   "kg": 300,
   "dona": 3000,
   "rows": 1,
   "last": "2026-06-24",
   "note": "WIP ledger yozuvi yo‘q — partiya (batch) ma’lumoti"
  },
  {
   "id": "e-6",
   "kind": "product-container",
   "source": "p-ikkiqavatarqon4kg",
   "target": "c-11",
   "table": "inventory",
   "joinBasis": "product nomi (text, normalizatsiya) — item_id bo‘sh",
   "kg": 3431.9,
   "dona": 735,
   "rows": 1
  },
  {
   "id": "e-7",
   "kind": "product-container",
   "source": "p-ikkiqavatarqon5kg",
   "target": "c-11",
   "table": "inventory",
   "joinBasis": "product nomi (text, normalizatsiya) — item_id bo‘sh",
   "kg": 4058.97,
   "dona": 815,
   "rows": 1
  },
  {
   "id": "e-8",
   "kind": "product-container",
   "source": "p-ikkiqavatarqon6kg",
   "target": "c-11",
   "table": "inventory",
   "joinBasis": "product nomi (text, normalizatsiya) — item_id bo‘sh",
   "kg": 2812.67,
   "dona": 479,
   "rows": 1
  },
  {
   "id": "e-9",
   "kind": "product-container",
   "source": "p-kurtkatros45kg",
   "target": "c-11",
   "table": "inventory",
   "joinBasis": "product nomi (text, normalizatsiya) — item_id bo‘sh",
   "kg": 151.9,
   "dona": 26,
   "rows": 1
  },
  {
   "id": "e-10",
   "kind": "product-container",
   "source": "p-qopip100talik",
   "target": "c-22",
   "table": "inventory",
   "joinBasis": "product nomi (text, normalizatsiya) — item_id bo‘sh",
   "kg": 6348,
   "dona": 55200,
   "rows": 1
  }
 ],
 "supplyEdges": [],
 "gaps": [
  {
   "code": "NO_RECEIVE_DATA",
   "title": "Container → Bo‘lim oqimi: ma’lumot yo‘q",
   "detail": "wip_movements jadvalida RECEIVE turidagi yozuv 0 ta (jami 171 ta yozuv — barchasi PRODUCE). Xomashyo konteynerdan bo‘limga kirim hech qachon ro‘yxatga olinmagan, shuning uchun bu chiziqlar chizilmaydi. Kirim yozila boshlagach oqim avtomatik paydo bo‘ladi."
  },
  {
   "code": "NEGATIVE_WIP",
   "title": "Arqon Bo‘lim 3: WIP manfiy",
   "detail": "Kirim 0 kg, chiqim 8964.77 kg — balans -8964.77 kg. Bu real database holati, yashirilmagan."
  },
  {
   "code": "ITEM_LINKS_EMPTY",
   "title": "item_id bog‘lari bo‘sh — text-nom bog‘lanish",
   "detail": "wip_movements 0/171, batches 0/280, products 0/117, BOM 0/62 item_id bilan bog‘langan. Graf ehtiyotkor nom-normalizatsiya (apostrof variantlari) orqali bog’laydi; ma’lumot o‘zgartirilmaydi."
  },
  {
   "code": "PURPOSE_MISMATCH",
   "title": "purpose ≠ kontent: C-03, C-04, C-08, C-09, C-13, C-15",
   "detail": "C-03: DB purpose='raw', kontent=finished (0 kg). Grafda kontent bo‘yicha ko‘rsatiladi, DB qiymati O‘ZGARTIRILMAYDI. C-04: DB purpose='finished', kontent=raw (6363.3 kg). Grafda kontent bo‘yicha ko‘rsatiladi, DB qiymati O‘ZGARTIRILMAYDI. C-08: DB purpose='raw', kontent=finished (0 kg). Grafda kontent bo‘yicha ko‘rsatiladi, DB qiymati O‘ZGARTIRILMAYDI. C-09: DB purpose='raw', kontent=finished (0 kg). Grafda kontent bo‘yicha ko‘rsatiladi, DB qiymati O‘ZGARTIRILMAYDI. C-13: DB purpose='raw', kontent=finished (0 kg). Grafda kontent bo‘yicha ko‘rsatiladi, DB qiymati O‘ZGARTIRILMAYDI. C-15: DB purpose='finished', kontent=raw (13020 kg). Grafda kontent bo‘yicha ko‘rsatiladi, DB qiymati O‘ZGARTIRILMAYDI."
  },
  {
   "code": "UNATTRIBUTED_BATCHES",
   "title": "Bo‘limga biriktirilmagan partiyalar: 71 ta",
   "detail": "9 xil mahsulot, 0.00 kg / 82748 dona partiya production_line_id=NULL. Grafda chizilmaydi (taxmin qilinmaydi), faqat shu yerda qayd etiladi."
  }
 ],
 "meta": {
  "unattributedBatches": {
   "products": 9,
   "kg": 0,
   "dona": 82748,
   "batches": 71
  },
  "dataQuality": {
   "wipItemLinked": "0/171",
   "batchesItemLinked": "0/280",
   "productsItemLinked": "0/117",
   "bomItemLinked": "0/62"
  },
  "pins": "inv=140 · mov=730 · BASELINE=110 · items=94 · pos=97 · LOADED=9 · wipmov=171 · batches=280 · bom=62",
  "classificationSource": "inventory.product_type (kontent-based) — warehouses.purpose EMAS"
 }
} as unknown as GraphFixture;
