// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/production-flow/FlowMap.tsx": () => import("../components/mockups/production-flow/FlowMap.tsx")
};
